import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@repo/shadcn-next/styles/globals.css';
import React from 'react';
import { themes } from '@repo/zod-schemas/constants/themes.js';
import { ThemeProvider } from 'context/theme-provider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          themes={themes}
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
